--  1. sofom
CREATE TABLE sofom (
    id_sofom        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(255) NOT NULL,
    rfc             VARCHAR(13) NOT NULL UNIQUE,
    dns_exclusivo   VARCHAR(255),
    fecha_registro  DATE NOT NULL,
    activa          BOOLEAN NOT NULL DEFAULT TRUE
);

--  2. sucursal
CREATE TABLE sucursal (
    id_sucursal     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sofom        INT NOT NULL,
    nombre_sucursal VARCHAR(255) NOT NULL,
    tipo            VARCHAR(100) CHECK (tipo IN ('MATRIZ', 'REGIONAL', 'AGENCIA', 'DIGITAL')),
    activa          BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY (id_sofom) REFERENCES sofom(id_sofom) ON UPDATE CASCADE ON DELETE RESTRICT
);

--  3. rol
CREATE TABLE rol (
    id_rol          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol      VARCHAR(100) NOT NULL UNIQUE,
    descripcion     TEXT,
    permisos_json   JSONB
);

--  4. tipo_documento
CREATE TABLE tipo_documento (
    id_tipo_doc     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sofom        INT NOT NULL,
    nombre_tipo     VARCHAR(150) NOT NULL,
    descripcion     TEXT,
    obligatorio     BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (id_sofom) REFERENCES sofom(id_sofom) ON UPDATE CASCADE ON DELETE RESTRICT
);

--  5. usuario
CREATE TABLE usuario (
    id_usuario      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(150) NOT NULL,
    apellido        VARCHAR(150) NOT NULL,
    email           VARCHAR(255) NOT NULL UNIQUE,
    id_rol          INT NOT NULL,
    fecha_alta      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    activo          BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY (id_rol) REFERENCES rol(id_rol) ON UPDATE CASCADE ON DELETE RESTRICT
);

--  6. cliente
CREATE TABLE cliente (
    id_cliente          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_razon_social VARCHAR(255) NOT NULL,
    tipo_persona        VARCHAR(10) NOT NULL CHECK (tipo_persona IN ('FISICA', 'MORAL')),
    rfc                 VARCHAR(13),
    curp                VARCHAR(18),
    nacionalidad        VARCHAR(100),
    es_pep              BOOLEAN NOT NULL DEFAULT FALSE,
    estatus             VARCHAR(20) NOT NULL DEFAULT 'ACTIVO' CHECK (estatus IN ('ACTIVO', 'INACTIVO', 'BLOQUEADO', 'BAJA')),
    id_analista         INT,
    fecha_alta          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (id_analista) REFERENCES usuario(id_usuario) ON UPDATE CASCADE ON DELETE SET NULL
);

--  7. domicilio
CREATE TABLE domicilio (
    id_domicilio    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente      INT NOT NULL,
    calle           VARCHAR(255),
    colonia         VARCHAR(150),
    ciudad          VARCHAR(150),
    estado          VARCHAR(100),
    pais            VARCHAR(100),
    tipo_domicilio  VARCHAR(30) CHECK (tipo_domicilio IN ('FISCAL', 'COMERCIAL', 'PARTICULAR')),
    id_sucursal     INT,
    FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (id_sucursal) REFERENCES sucursal(id_sucursal) ON UPDATE CASCADE ON DELETE SET NULL
);

--  8. documento
CREATE TABLE documento (
    id_documento    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente      INT NOT NULL,
    id_tipo_doc     INT NOT NULL,
    ruta_archivo    VARCHAR(500),
    estatus         VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE' CHECK (estatus IN ('PENDIENTE', 'APROBADO', 'RECHAZADO', 'VENCIDO')),
    id_validador    INT,
    fecha_carga     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (id_tipo_doc) REFERENCES tipo_documento(id_tipo_doc) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (id_validador) REFERENCES usuario(id_usuario) ON UPDATE CASCADE ON DELETE SET NULL
);

--  9. contrato
CREATE TABLE contrato (
    id_contrato     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente      INT NOT NULL,
    numero_contrato VARCHAR(100) NOT NULL UNIQUE,
    tipo_producto   VARCHAR(100),
    fecha_inicio    DATE,
    estatus         VARCHAR(20) NOT NULL DEFAULT 'VIGENTE' CHECK (estatus IN ('VIGENTE', 'VENCIDO', 'CANCELADO', 'SUSPENDIDO')),
    id_analista     INT,
    FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (id_analista) REFERENCES usuario(id_usuario) ON UPDATE CASCADE ON DELETE SET NULL
);

--  10. operacion
CREATE TABLE operacion (
    id_operacion    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente      INT NOT NULL,
    id_contrato     INT NOT NULL,
    tipo_operacion  VARCHAR(100),
    monto           NUMERIC(18, 2) NOT NULL CHECK (monto >= 0),
    moneda          VARCHAR(10) NOT NULL DEFAULT 'MXN',
    fecha_operacion DATE NOT NULL,
    id_analista     INT,
    FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (id_contrato) REFERENCES contrato(id_contrato) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (id_analista) REFERENCES usuario(id_usuario) ON UPDATE CASCADE ON DELETE SET NULL
);

--  11. reporte
CREATE TABLE reporte (
    id_reporte        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_reporte      VARCHAR(150),
    canal_envio       VARCHAR(100),
    fecha_generacion  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    estatus_envio     VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE' CHECK (estatus_envio IN ('PENDIENTE', 'ENVIADO', 'RECHAZADO', 'CONFIRMADO')),
    id_oficial        INT,
    periodo_reportado VARCHAR(50),
    FOREIGN KEY (id_oficial) REFERENCES usuario(id_usuario) ON UPDATE CASCADE ON DELETE SET NULL
);

--  12. regla_alerta
CREATE TABLE regla_alerta (
    id_regla          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_regla      VARCHAR(150) NOT NULL,
    umbral_monto      NUMERIC(18, 2) CHECK (umbral_monto IS NULL OR umbral_monto >= 0),
    umbral_frecuencia INT CHECK (umbral_frecuencia IS NULL OR umbral_frecuencia > 0),
    activa            BOOLEAN NOT NULL DEFAULT TRUE,
    id_admin          INT,
    FOREIGN KEY (id_admin) REFERENCES usuario(id_usuario) ON UPDATE CASCADE ON DELETE SET NULL
);

--  13. alerta
CREATE TABLE alerta (
    id_alerta        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_operacion     INT NOT NULL,
    id_cliente       INT NOT NULL,
    id_regla         INT NOT NULL,
    tipo_alerta      VARCHAR(100),
    estatus          VARCHAR(20) NOT NULL DEFAULT 'ABIERTA' CHECK (estatus IN ('ABIERTA', 'EN_REVISION', 'CERRADA', 'ESCALADA')),
    fecha_generacion TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    id_oficial       INT,
    id_reporte       INT,
    FOREIGN KEY (id_operacion) REFERENCES operacion(id_operacion) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (id_regla) REFERENCES regla_alerta(id_regla) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (id_oficial) REFERENCES usuario(id_usuario) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY (id_reporte) REFERENCES reporte(id_reporte) ON UPDATE CASCADE ON DELETE SET NULL
);

--  14. perfil_riesgo
CREATE TABLE perfil_riesgo (
    id_perfil     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente    INT NOT NULL,
    nivel_riesgo  VARCHAR(20) CHECK (nivel_riesgo IN ('BAJO', 'MEDIO', 'ALTO', 'MUY_ALTO')),
    score         NUMERIC(5, 2) CHECK (score IS NULL OR (score >= 0 AND score <= 100)),
    fecha_calculo TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    id_oficial    INT,
    FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (id_oficial) REFERENCES usuario(id_usuario) ON UPDATE CASCADE ON DELETE SET NULL
);

--  15. reporte_interno
CREATE TABLE reporte_interno (
    id_reporte_int INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente     INT NOT NULL,
    descripcion    TEXT,
    es_anonimo     BOOLEAN NOT NULL DEFAULT FALSE,
    estatus        VARCHAR(20) NOT NULL DEFAULT 'ABIERTO' CHECK (estatus IN ('ABIERTO', 'EN_PROCESO', 'CERRADO', 'ARCHIVADO')),
    fecha_reporte  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    id_reportante  INT,
    CHECK ((es_anonimo = TRUE AND id_reportante IS NULL) OR (es_anonimo = FALSE AND id_reportante IS NOT NULL)),
    FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (id_reportante) REFERENCES usuario(id_usuario) ON UPDATE CASCADE ON DELETE SET NULL
);

--  16. historial_cambios
CREATE TABLE historial_cambios (
    id_historial     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario       INT NOT NULL,
    accion           VARCHAR(100) NOT NULL CHECK (accion IN ('INSERT', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'EXPORT')),
    entidad_afectada VARCHAR(150),
    fecha_hora       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ip_address       VARCHAR(45),
    campo_modificado VARCHAR(150),
    valor_anterior   TEXT,
    valor_nuevo      TEXT,
    FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario) ON UPDATE CASCADE ON DELETE RESTRICT
);
