--  1. sofom
CREATE TABLE sofom (
    id_sofom        INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(255) NOT NULL,
    rfc             VARCHAR(13)  NOT NULL,
    dns_exclusivo   VARCHAR(255),
    fecha_registro  DATE         NOT NULL,
    activa          BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_actualizacion TIMESTAMPTZ,

    CONSTRAINT uq_sofom_rfc UNIQUE (rfc)
);


--  2. sucursal
CREATE TABLE sucursal (
    id_sucursal     INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sofom        INT          NOT NULL,
    nombre_sucursal VARCHAR(255) NOT NULL,
    tipo            VARCHAR(100),
    activa          BOOLEAN      NOT NULL DEFAULT TRUE,

    CONSTRAINT chk_sucursal_tipo
        CHECK (tipo IN ('MATRIZ', 'REGIONAL', 'AGENCIA', 'DIGITAL')),

    CONSTRAINT fk_sucursal_sofom
        FOREIGN KEY (id_sofom)
        REFERENCES sofom(id_sofom)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);


--  3. rol
CREATE TABLE rol (
    id_rol      INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol  VARCHAR(100) NOT NULL,
    descripcion TEXT,
    permisos_json JSONB,

    CONSTRAINT uq_rol_nombre UNIQUE (nombre_rol)
);


--  4. tipo_documento
CREATE TABLE tipo_documento (
    id_tipo_doc  INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sofom     INT          NOT NULL,
    nombre_tipo  VARCHAR(150) NOT NULL,
    descripcion  TEXT,
    obligatorio  BOOLEAN      NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_tipodoc_sofom
        FOREIGN KEY (id_sofom)
        REFERENCES sofom(id_sofom)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);


--  5. usuario
CREATE TABLE usuario (
    id_usuario   INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(150) NOT NULL,
    apellido     VARCHAR(150) NOT NULL,
    email        VARCHAR(255) NOT NULL,
    id_rol       INT          NOT NULL,
    fecha_alta   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    activo       BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_actualizacion TIMESTAMPTZ,

    CONSTRAINT uq_usuario_email UNIQUE (email),

    CONSTRAINT fk_usuario_rol
        FOREIGN KEY (id_rol)
        REFERENCES rol(id_rol)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);


--  6. cliente
CREATE TABLE cliente (
    id_cliente          INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_razon_social VARCHAR(255) NOT NULL,
    tipo_persona        VARCHAR(10)  NOT NULL,
    rfc                 VARCHAR(13),
    curp                VARCHAR(18),
    nacionalidad        VARCHAR(100),
    es_pep              BOOLEAN      NOT NULL DEFAULT FALSE,
    estatus             VARCHAR(20)  NOT NULL DEFAULT 'ACTIVO',
    id_analista         INT,
    fecha_alta          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ,

    CONSTRAINT chk_cliente_tipo_persona
        CHECK (tipo_persona IN ('FISICA', 'MORAL')),

    CONSTRAINT chk_cliente_estatus
        CHECK (estatus IN ('ACTIVO', 'INACTIVO', 'BLOQUEADO', 'BAJA')),

    CONSTRAINT uq_cliente_rfc UNIQUE (rfc),

    CONSTRAINT fk_cliente_analista
        FOREIGN KEY (id_analista)
        REFERENCES usuario(id_usuario)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);


--  7. domicilio
CREATE TABLE domicilio (
    id_domicilio   INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente     INT          NOT NULL,
    calle          VARCHAR(255),
    colonia        VARCHAR(150),
    ciudad         VARCHAR(150),
    estado         VARCHAR(100),
    pais           VARCHAR(100),
    tipo_domicilio VARCHAR(30),
    id_sucursal    INT,

    CONSTRAINT chk_domicilio_tipo
        CHECK (tipo_domicilio IN ('FISCAL', 'COMERCIAL', 'PARTICULAR')),

    CONSTRAINT fk_domicilio_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES cliente(id_cliente)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_domicilio_sucursal
        FOREIGN KEY (id_sucursal)
        REFERENCES sucursal(id_sucursal)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);


--  8. documento
CREATE TABLE documento (
    id_documento  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente    INT          NOT NULL,
    id_tipo_doc   INT          NOT NULL,
    ruta_archivo  VARCHAR(500),
    estatus       VARCHAR(20)  NOT NULL DEFAULT 'PENDIENTE',
    id_validador  INT,
    fecha_carga   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    fecha_actualizacion TIMESTAMPTZ,

    CONSTRAINT chk_documento_estatus
        CHECK (estatus IN ('PENDIENTE', 'APROBADO', 'RECHAZADO', 'VENCIDO')),

    CONSTRAINT fk_documento_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES cliente(id_cliente)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_documento_tipodoc
        FOREIGN KEY (id_tipo_doc)
        REFERENCES tipo_documento(id_tipo_doc)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_documento_validador
        FOREIGN KEY (id_validador)
        REFERENCES usuario(id_usuario)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);


--  9. contrato
CREATE TABLE contrato (
    id_contrato     INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente      INT          NOT NULL,
    numero_contrato VARCHAR(100) NOT NULL,
    tipo_producto   VARCHAR(100),
    fecha_inicio    DATE,
    estatus         VARCHAR(20)  NOT NULL DEFAULT 'VIGENTE',
    id_analista     INT,
    fecha_actualizacion TIMESTAMPTZ,

    CONSTRAINT uq_contrato_numero UNIQUE (numero_contrato),

    CONSTRAINT chk_contrato_estatus
        CHECK (estatus IN ('VIGENTE', 'VENCIDO', 'CANCELADO', 'SUSPENDIDO')),

    CONSTRAINT fk_contrato_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES cliente(id_cliente)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_contrato_analista
        FOREIGN KEY (id_analista)
        REFERENCES usuario(id_usuario)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);


--  10. operacion
CREATE TABLE operacion (
    id_operacion    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente      INT          NOT NULL,
    id_contrato     INT          NOT NULL,
    tipo_operacion  VARCHAR(100),
    monto           NUMERIC(18, 2) NOT NULL,
    moneda          VARCHAR(10)  NOT NULL DEFAULT 'MXN',
    fecha_operacion DATE         NOT NULL,
    id_analista     INT,

    CONSTRAINT chk_operacion_monto
        CHECK (monto > 0),

    CONSTRAINT fk_operacion_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES cliente(id_cliente)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_operacion_contrato
        FOREIGN KEY (id_contrato)
        REFERENCES contrato(id_contrato)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_operacion_analista
        FOREIGN KEY (id_analista)
        REFERENCES usuario(id_usuario)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);


--  11. reporte
CREATE TABLE reporte (
    id_reporte        INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_reporte      VARCHAR(150),
    canal_envio       VARCHAR(100),
    fecha_generacion  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    estatus_envio     VARCHAR(20)  NOT NULL DEFAULT 'PENDIENTE',
    id_oficial        INT,
    periodo_reportado VARCHAR(50),
    fecha_actualizacion TIMESTAMPTZ,

    CONSTRAINT chk_reporte_estatus_envio
        CHECK (estatus_envio IN ('PENDIENTE', 'ENVIADO', 'RECHAZADO', 'CONFIRMADO')),

    CONSTRAINT fk_reporte_oficial
        FOREIGN KEY (id_oficial)
        REFERENCES usuario(id_usuario)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);


--  12. regla_alerta
CREATE TABLE regla_alerta (
    id_regla          INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_regla      VARCHAR(150) NOT NULL,
    umbral_monto      NUMERIC(18, 2),
    umbral_frecuencia INT,
    activa            BOOLEAN      NOT NULL DEFAULT TRUE,
    id_admin          INT,

    CONSTRAINT chk_regla_umbral_monto
        CHECK (umbral_monto IS NULL OR umbral_monto >= 0),

    CONSTRAINT chk_regla_umbral_frecuencia
        CHECK (umbral_frecuencia IS NULL OR umbral_frecuencia > 0),

    CONSTRAINT fk_regla_admin
        FOREIGN KEY (id_admin)
        REFERENCES usuario(id_usuario)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);


--  13. alerta
CREATE TABLE alerta (
    id_alerta        BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_operacion     BIGINT       NOT NULL,
    id_cliente       INT          NOT NULL,
    id_regla         INT          NOT NULL,
    tipo_alerta      VARCHAR(100),
    estatus          VARCHAR(20)  NOT NULL DEFAULT 'ABIERTA',
    fecha_generacion TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    id_oficial       INT,
    id_reporte       INT,
    fecha_actualizacion TIMESTAMPTZ,

    CONSTRAINT chk_alerta_estatus
        CHECK (estatus IN ('ABIERTA', 'EN_REVISION', 'CERRADA', 'ESCALADA')),

    CONSTRAINT fk_alerta_operacion
        FOREIGN KEY (id_operacion)
        REFERENCES operacion(id_operacion)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_alerta_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES cliente(id_cliente)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_alerta_regla
        FOREIGN KEY (id_regla)
        REFERENCES regla_alerta(id_regla)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_alerta_oficial
        FOREIGN KEY (id_oficial)
        REFERENCES usuario(id_usuario)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_alerta_reporte
        FOREIGN KEY (id_reporte)
        REFERENCES reporte(id_reporte)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);


--  14. perfil_riesgo
CREATE TABLE perfil_riesgo (
    id_perfil    INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente   INT          NOT NULL,
    nivel_riesgo VARCHAR(20),
    score        NUMERIC(5, 2),
    fecha_calculo TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    id_oficial   INT,

    CONSTRAINT chk_perfil_nivel_riesgo
        CHECK (nivel_riesgo IN ('BAJO', 'MEDIO', 'ALTO', 'MUY_ALTO')),

    CONSTRAINT chk_perfil_score
        CHECK (score IS NULL OR (score >= 0 AND score <= 100)),

    CONSTRAINT fk_perfil_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES cliente(id_cliente)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_perfil_oficial
        FOREIGN KEY (id_oficial)
        REFERENCES usuario(id_usuario)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);


--  15. reporte_interno
CREATE TABLE reporte_interno (
    id_reporte_int INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente     INT          NOT NULL,
    descripcion    TEXT,
    es_anonimo     BOOLEAN      NOT NULL DEFAULT FALSE,
    estatus        VARCHAR(20)  NOT NULL DEFAULT 'ABIERTO',
    fecha_reporte  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    id_reportante  INT,
    fecha_actualizacion TIMESTAMPTZ,

    CONSTRAINT chk_repint_estatus
        CHECK (estatus IN ('ABIERTO', 'EN_PROCESO', 'CERRADO', 'ARCHIVADO')),

    CONSTRAINT chk_repint_anonimo
        CHECK (
            (es_anonimo = TRUE  AND id_reportante IS NULL) OR
            (es_anonimo = FALSE AND id_reportante IS NOT NULL)
        ),

    CONSTRAINT fk_repint_cliente
        FOREIGN KEY (id_cliente)
        REFERENCES cliente(id_cliente)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_repint_reportante
        FOREIGN KEY (id_reportante)
        REFERENCES usuario(id_usuario)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);


--  16. historial_cambios
CREATE TABLE historial_cambios (
    id_historial     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario       INT          NOT NULL,
    accion           VARCHAR(100) NOT NULL,
    entidad_afectada VARCHAR(150),
    fecha_hora       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    ip_address       VARCHAR(45),
    campo_modificado VARCHAR(150),
    valor_anterior   TEXT,
    valor_nuevo      TEXT,

    CONSTRAINT chk_historial_accion
        CHECK (accion IN ('INSERT', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'EXPORT')),

    CONSTRAINT fk_historial_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);
